# Cloudflare Pages Configuration
# This file ensures proper D1 database bindings for Pages deployments

[[pages.env.production.d1_databases]]
binding = "DB"
database_name = "contact-us-personal-site"
database_id = "59fd9243-14b4-4f0a-9cb8-a1960f605642"

[pages.env.production.vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1420858430486347827/9abrx8-ImkXY1heRloZ8QxtNoDlKJvPBGf-is5kOpXaqpujK60txO3qbFwXnVz32nk6v"