name = "personalsite"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "contact-us-personal-site"
database_id = "59fd9243-14b4-4f0a-9cb8-a1960f605642"

[vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1420858430486347827/9abrx8-ImkXY1heRloZ8QxtNoDlKJvPBGf-is5kOpXaqpujK60txO3qbFwXnVz32nk6v"
